// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_fluence

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func FluenceProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Required:            true,
				Description:         "API key for authenticating to Fluence",
				MarkdownDescription: "API key for authenticating to Fluence",
			},
			"api_url": schema.StringAttribute{
				Optional:            true,
				Description:         "Base URL for the Fluence API",
				MarkdownDescription: "Base URL for the Fluence API",
			},
		},
	}
}

type FluenceModel struct {
	ApiKey types.String `tfsdk:"api_key"`
	ApiUrl types.String `tfsdk:"api_url"`
}
