// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_ssh_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SshKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Computed: true,
			},
			"algorithm": schema.StringAttribute{
				Computed:            true,
				Description:         "SSH Key algorithm",
				MarkdownDescription: "SSH Key algorithm",
			},
			"comment": schema.StringAttribute{
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"fingerprint": schema.StringAttribute{
				Computed:            true,
				Description:         "ssh key fingerprint in base64",
				MarkdownDescription: "ssh key fingerprint in base64",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A human-readable display name for this key, used to easily identify the SSH keys when they are displayed.",
				MarkdownDescription: "A human-readable display name for this key, used to easily identify the SSH keys when they are displayed.",
			},
			"public_key": schema.StringAttribute{
				Required:            true,
				Description:         "The public key in OpenSSH format. Supported algorithms are:\n- ECDSA (nistp256, nistp384, nistp521)\n- RSA\n- ED25519",
				MarkdownDescription: "The public key in OpenSSH format. Supported algorithms are:\n- ECDSA (nistp256, nistp384, nistp521)\n- RSA\n- ED25519",
			},
		},
	}
}

type SshKeyModel struct {
	Active      types.Bool   `tfsdk:"active"`
	Algorithm   types.String `tfsdk:"algorithm"`
	Comment     types.String `tfsdk:"comment"`
	CreatedAt   types.String `tfsdk:"created_at"`
	Fingerprint types.String `tfsdk:"fingerprint"`
	Name        types.String `tfsdk:"name"`
	PublicKey   types.String `tfsdk:"public_key"`
}
